import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Landing Page specific colors
        "landing-tertiary": "#006461",
        "landing-surface-container-high": "#e2e9ec",
        "landing-inverse-primary": "#c6bfff",
        "landing-on-surface": "#161d1f",
        "landing-outline-variant": "#c8c4d7",
        "landing-on-primary": "#ffffff",
        "landing-primary-fixed": "#e4dfff",
        "landing-on-primary-container": "#faf6ff",
        "landing-inverse-on-surface": "#ebf2f4",
        "landing-primary": "#5341cd",
        "landing-secondary-fixed-dim": "#f0bf63",
        "landing-primary-container": "#6c5ce7",
        "landing-on-surface-variant": "#474554",
        "landing-on-tertiary-container": "#d9fffc",
        "landing-on-primary-fixed": "#160066",
        "landing-surface-container-lowest": "#ffffff",
        "landing-on-tertiary": "#ffffff",
        "landing-on-tertiary-fixed-variant": "#00504e",
        "landing-on-secondary-fixed-variant": "#5e4200",
        "landing-on-error": "#ffffff",
        "landing-tertiary-fixed-dim": "#2edcd7",
        "landing-error": "#ba1a1a",
        "landing-error-container": "#ffdad6",
        "landing-on-tertiary-fixed": "#00201f",
        "landing-on-secondary-container": "#785500",
        "landing-background": "#f4fafd",
        "landing-secondary": "#7c5800",
        "landing-surface-tint": "#5847d2",
        "landing-surface-dim": "#d4dbdd",
        "landing-inverse-surface": "#2b3234",
        "landing-secondary-fixed": "#ffdea7",
        "landing-surface-variant": "#dde4e6",
        "landing-on-secondary-fixed": "#271900",
        "landing-secondary-container": "#ffcd70",
        "landing-on-error-container": "#93000a",
        "landing-tertiary-fixed": "#5af9f3",
        "landing-surface-container": "#e8eff1",
        "landing-surface-container-low": "#eef5f7",
        "landing-on-secondary": "#ffffff",
        "landing-on-background": "#161d1f",
        "landing-primary-fixed-dim": "#c6bfff",
        "landing-surface-container-highest": "#dde4e6",
        "landing-outline": "#787586",
        "landing-surface": "#f4fafd",
        "landing-on-primary-fixed-variant": "#4029ba",
        "landing-tertiary-container": "#007f7c",
        "landing-surface-bright": "#f4fafd"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "landing-unit-xl": "40px",
        "landing-margin-mobile": "20px",
        "landing-unit-xs": "4px",
        "landing-container-max-width": "1280px",
        "landing-gutter": "24px",
        "landing-unit-sm": "8px",
        "landing-unit-md": "16px",
        "landing-unit-lg": "24px",
        "landing-margin-desktop": "64px"
      },
      fontFamily: {
        "headline-lg": ["var(--font-montserrat)"],
        "headline-lg-mobile": ["var(--font-montserrat)"],
        "body-md": ["var(--font-be-vietnam-pro)"],
        "headline-md": ["var(--font-montserrat)"],
        "headline-xl": ["var(--font-montserrat)"],
        "label-md": ["var(--font-be-vietnam-pro)"],
        "label-sm": ["var(--font-be-vietnam-pro)"],
        "body-lg": ["var(--font-be-vietnam-pro)"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.25", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
} satisfies Config;

export default config;
